In [1]:
import pandas as pd
df=pd.read_csv("retail_sales_dataset.csv")

In [2]:
df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

## Data Cleaning and Preparation

First, let's examine the data types and check for missing values.

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   object
 2   Customer ID       1000 non-null   object
 3   Gender            1000 non-null   object
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   object
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), object(4)
memory usage: 70.4+ KB

In [7]:
a=df.isnull().sum()
df.isnull()
print("Number of duplicate rows:",a)

Dataset after introducing nulls and duplicates:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1050 non-null   int64
 1   Date              1050 non-null   object
 2   Customer ID       1050 non-null   object
 3   Gender            1029 non-null   object
 4   Age               950 non-null    float64
 5   Product Category  1050 non-null   object
 6   Quantity          1050 non-null   int64
 7   Price per Unit    1050 non-null   int64
 8   Total Amount      1050 non-null   int64
dtypes: float64(1), int64(4), object(4)
memory usage: 74.0+ KB

None

Transaction ID        0
Date                  0
Customer ID           0
Gender               21
Age                 100
Product Category      0
Quantity              0
Price per Unit        0
Total Amount          0
dtype: int64

Number of duplicate rows: 50

### Cleaning Duplicates and Null Values

Now that we have introduced issues, let's clean the dataset by removing duplicate rows and handling missing values. For 'Age', we'll fill missing values with the mean, and for 'Gender', we'll fill with the mode (most frequent value).

In [8]:
# Remove duplicate rows
df.drop_duplicates(inplace=True)

df['Age'].fillna(df['Age'].mean(), inplace=True)

mode_gender = df['Gender'].mode()[0]
df['Gender'].fillna(mode_gender, inplace=True)

print("Dataset after cleaning:")
display(df.info())
display(df.isnull().sum())
print(f"Number of duplicate rows: {df.duplicated().sum()}")

Dataset after cleaning:
<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   object
 2   Customer ID       1000 non-null   object
 3   Gender            1000 non-null   object
 4   Age               1000 non-null   float64
 5   Product Category  1000 non-null   object
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: float64(1), int64(4), object(4)
memory usage: 78.1+ KB

/tmp/ipykernel_16750/3373853331.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)
/tmp/ipykernel_16750/3373853331.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].fillna(mode_gender, inplace=True)

None

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

Number of duplicate rows: 0

In [9]:
df['Date'] = pd.to_datetime(df['Date'])

print("Data types after converting 'Date':")
display(df.info())

Data types after converting 'Date':
<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   datetime64[ns]
 2   Customer ID       1000 non-null   object
 3   Gender            1000 non-null   object
 4   Age               1000 non-null   float64
 5   Product Category  1000 non-null   object
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(4), object(3)
memory usage: 78.1+ KB

None

In [10]:
df['Gender'] = df['Gender'].str.lower()
df['Product Category'] = df['Product Category'].str.lower()

print("Unique values in 'Gender' after standardization:")
display(df['Gender'].unique())
print("Unique values in 'Product Category' after standardization:")
display(df['Product Category'].unique())

Unique values in 'Gender' after standardization:

array(['male', 'female'], dtype=object)

Unique values in 'Product Category' after standardization:

array(['beauty', 'clothing', 'electronics'], dtype=object)

In [11]:
Q1 = df['Total Amount'].quantile(0.25)
Q3 = df['Total Amount'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

df_cleaned = df[(df['Total Amount'] >= lower_bound) & (df['Total Amount'] <= upper_bound)]

print(f"Original number of rows: {len(df)}")
print(f"Number of rows after outlier removal: {len(df_cleaned)}")
print("Dataset head after outlier removal:")
display(df_cleaned.head())

Original number of rows: 1000
Number of rows after outlier removal: 1000
Dataset head after outlier removal:

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,male,34.0,beauty,3,50,150
1,2,2023-02-27,CUST002,female,26.0,clothing,2,500,1000
2,3,2023-01-13,CUST003,male,50.0,electronics,1,30,30
3,4,2023-05-21,CUST004,male,37.0,clothing,1,500,500
4,5,2023-05-06,CUST005,male,30.0,beauty,2,50,100

In [12]:
df_cleaned.to_csv('retail_sales_cleaned_dataset.csv', index=False)
print("Cleaned data saved to 'retail_sales_cleaned_dataset.csv'")
print("You can download this file from the 'Files' tab on the left sidebar.")

Cleaned data saved to 'retail_sales_cleaned_dataset.csv'
You can download this file from the 'Files' tab on the left sidebar.